### ISSUE TITLE
Bitmovin and exoplayer conflicting dependencies in latest version

### ISSUE THREAD

**Issue by Developer-LokikSoni** [bitmovin/bitmovin-analytics-collector-android#89]
I am using both Exoplayer and Bitmovin core libraries in my project

compile "com.bitmovin.player:playercore:$bitmovin_version"
compile "ccom.google.android.exoplayer:exoplayer-core"

    bitmovin_version            = '2.36.1'
    exoplayer_version           = '2.11.4'

When I run my app it gives me this error

Program type already present: com.google.android.exoplayer2.ui.BuildConfig

How can I exclude Exoplayer files from Bitmovin?

**Comment by dweinber** [comment]
Hi,
It is not possible out of the box to use Bitmovin Player and ExoPlayer in the same project. It is possible if the Bitmovin Player releases are used which are postfixed with `+jason` (available in the same Maven repository), but please be aware that the version of Exoplayer and Bitmovin's Exoplayer must match. We'll put up an FAQ on bitmovin.com/docs soon.
As this issue is not related to the analytics collector, I'm closing this issue. Please check https://github.com/bitmovin/bitmovin-analytics-collector-android#support in case you need any further assistance.
